### ISSUE TITLE
size mismatch

### ISSUE THREAD

**Issue by headre** [hongsukchoi/TCMR_RELEASE#16]
Thanks for your great work! When I tested the demo provided, some problem occurred while loading models:
```
Traceback (most recent call last):
  File "demo.py", line 376, in <module>
    main(args)
  File "demo.py", line 111, in main
    model.load_state_dict(ckpt, strict=False)
  File "/opt/data/private/TCMR/TCMR_RELEASE/tcmr-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TCMR:
	size mismatch for regressor.smpl.shapedirs: copying a param with shape torch.Size([6890, 3, 10]) from checkpoint, the shape in current model is torch.Size([6890, 3, 300]).
```
I wonder why and what to do. THX.

**Comment by hongsukchoi** [comment]
Hi, and sorry for the late reply...

I think the error is due to version matching of SMPL weights. 
Refer to this issue!
https://githubmemory.com/repo/Jeff-sjtu/HybrIK/issues/24

**Comment by fengzehui0422** [comment]
> Hi, and sorry for the late reply...
> 
> I think the error is due to version matching of SMPL weights. Refer to this issue! https://githubmemory.com/repo/Jeff-sjtu/HybrIK/issues/24

sorry，the  link is closed  how can I solve this ？THX
