### ISSUE TITLE
ValueError: Invalid device ID (0)

### ISSUE THREAD

**Issue by Mirandl** [hongsukchoi/TCMR_RELEASE#25]
Hi, I met this bug and don't know how to resolve it. I've tried to change the egl.py but it didn't work.
It may be similar to #7 and I have tried lots of methods after it but they don't work. 

I would VERY appreciate it if you can give me some advice. It has tortured me for a long time.

My environment is Ubuntu16.04 from a remote server, given 1 GPU only. 
------------------- 
Running "ffmpeg -i sample_demo.mp4 -r 30000/1001 -f image2 -v error /tmp/sample_demo_mp4/%06d.jpg"
Images saved to "/tmp/sample_demo_mp4"
Input video number of frames 122

Running Multi-Person-Tracker
100%|███████████████████████████████████████████| 11/11 [00:04<00:00,  2.48it/s]
Finished. Detection + Tracking FPS 27.49
=> loaded pretrained model from 'data/base_data/spin_model_checkpoint.pth.tar'
Load pretrained weights from './data/base_data/tcmr_demo_model.pth.tar'

Running TCMR on each person tracklet...
100%|█████████████████████████████████████████████| 5/5 [00:22<00:00,  4.53s/it]
TCMR FPS: 5.38
Total time spent: 36.98 seconds (including model loading time).
Total FPS (including model loading time): 3.30.
Get SMPL faces
Traceback (most recent call last):
  File "/root/data/meilin/TCMR/demo.py", line 376, in <module>
    main(args)
  File "/root/data/meilin/TCMR/demo.py", line 248, in main
    renderer = Renderer(resolution=(orig_width, orig_height), orig_img=True, wireframe=args.wireframe)
  File "/root/data/meilin/TCMR/lib/utils/renderer.py", line 47, in __init__
    point_size=1.0
  File "/usr/local/lib/python3.6/dist-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/usr/local/lib/python3.6/dist-packages/pyrender/offscreen.py", line 137, in _create
    egl_device = egl.get_device_by_index(device_id)
  File "/usr/local/lib/python3.6/dist-packages/pyrender/platforms/egl.py", line 83, in get_device_by_index
    raise ValueError('Invalid device ID ({})'.format(device_id, len(devices)))
ValueError: Invalid device ID (0)

Process finished with exit code 1

**Comment by hongsukchoi** [comment]
sometimes egl has inunderstandable bugs in my experience. did you try osmesa?

**Comment by lllllialois** [comment]
I meet the same bug and I want to ask you did you fixed it?
