### ISSUE TITLE
About reproducing repr_table4_3dpw_model.yaml

### ISSUE THREAD

**Issue by amituofo1996** [hongsukchoi/TCMR_RELEASE#31]
train.log is following
```
InstaVariety number of dataset objects 2086896
3DPW Dataset overlap ratio:  0.9375
Loaded 3dpw dataset from data/preprocessed_data/3dpw_train_occ_db.pt
is_train:  True
3dpw - number of dataset objects 22448
MPII3D Dataset overlap ratio:  0.9375
Loaded mpii3d dataset from data/preprocessed_data/mpii3d_train_scale12_occ_db.pt
is_train:  True
mpii3d - number of dataset objects 958944
Human36M Dataset overlap ratio:  0.9375
Loaded h36m dataset from data/preprocessed_data/h36m_train_25fps_occ_db.pt
is_train:  True
h36m - number of dataset objects 775296
3DPW Dataset overlap ratio:  0
Loaded 3dpw dataset from data/preprocessed_data/3dpw_val_db.pt
is_train:  False
3dpw - number of dataset objects 53
=> loaded pretrained model from 'data/base_data/spin_model_checkpoint.pth.tar'
Epoch 1/30
=> no checkpoint found at ''
(500/500) | Total: 0:03:40 | ETA: 0:00:01 | loss: 9.99 | 2d: 3.91 | 3d: 5.62  | loss_kp_2d: 2.671 | loss_kp_3d: 3.043 | data: 0.01 | forward: 0.05 | loss: 0.00 | backward: 0.06 | batch: 0.12
Traceback (most recent call last):
  File "/media/xf/F/code/TCMR_RELEASE-master/train.py", line 141, in <module>
    main(cfg)
  File "/media/xf/F/code/TCMR_RELEASE-master/train.py", line 131, in main
    debug_freq=cfg.DEBUG_FREQ,
  File "/media/xf/F/code/TCMR_RELEASE-master/lib/core/trainer.py", line 343, in fit
    self.validate()
  File "/media/xf/F/code/TCMR_RELEASE-master/lib/core/trainer.py", line 291, in validate
    for i, target in enumerate(self.valid_loader):
  File "/home/xf/miniconda3/envs/tcmr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/xf/miniconda3/envs/tcmr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/xf/miniconda3/envs/tcmr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/xf/miniconda3/envs/tcmr/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/xf/miniconda3/envs/tcmr/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xf/miniconda3/envs/tcmr/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xf/miniconda3/envs/tcmr/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/xf/F/code/TCMR_RELEASE-master/lib/dataset/_dataset_3d.py", line 86, in __getitem__
    return self.get_single_item(index)
  File "/media/xf/F/code/TCMR_RELEASE-master/lib/dataset/_dataset_3d.py", line 243, in get_single_item
    kp_3d_tensor[idx] = kp_3d[idx]
ValueError: could not broadcast input array from shape (49,3) into shape (14,3)
```

Only repr_table6_h36m_model.yaml is ok，and others experiment all facing this problem.They have same DATA_EVAL=ThreeDPW，I get confused of this. Could you help me？ Thanks

**Comment by hongsukchoi** [comment]
I think you parsed the data yourselves... and in that process you seem to miss to convert joint format to the (49,3), which is union of joint formats across different datasets.

**Comment by amituofo1996** [comment]
yes, I redownload your processed data and solved this problem
