### ISSUE TITLE
'Unable to load EGL library', "Could not find module 'EG' error..

### ISSUE THREAD

**Issue by dopeornope-Lee** [hongsukchoi/TCMR_RELEASE#37]
Running TCMR on each person tracklet...
  0%|                                                                                            | 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\ailab\lib\site-packages\OpenGL\platform\egl.py", line 67, in EGL
    return ctypesloader.loadLibrary(
  File "C:\Users\user\anaconda3\envs\ailab\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "C:\Users\user\anaconda3\envs\ailab\lib\ctypes\__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: ("Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\anaconda3\envs\ailab\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\user\anaconda3\envs\ailab\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\user\anaconda3\envs\ailab\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\user\anaconda3\envs\ailab\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\user\anaconda3\envs\ailab\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\user\anaconda3\envs\ailab\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\user\anaconda3\envs\ailab\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Desktop\NeRF\TCMR_RELEASE\demo.py", line 23, in <module>
    import pyrender
  File "C:\Users\user\anaconda3\envs\ailab\lib\site-packages\pyrender\__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "C:\Users\user\anaconda3\envs\ailab\lib\site-packages\pyrender\light.py", line 10, in <module>
    from OpenGL.GL import *
  File "C:\Users\user\anaconda3\envs\ailab\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "C:\Users\user\anaconda3\envs\ailab\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "C:\Users\user\anaconda3\envs\ailab\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "C:\Users\user\anaconda3\envs\ailab\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "C:\Users\user\anaconda3\envs\ailab\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "C:\Users\user\anaconda3\envs\ailab\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Users\user\anaconda3\envs\ailab\lib\site-packages\OpenGL\platform\egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "C:\Users\user\anaconda3\envs\ailab\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Users\user\anaconda3\envs\ailab\lib\site-packages\OpenGL\platform\egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', "Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)

**Comment by dopeornope-Lee** [comment]
How can I solve this problem???

**Comment by hongsukchoi** [comment]
I don't use windows and am not an expert on these issues :( I heard OSMESA instead of EGL causes less problems
