### ISSUE TITLE
14 joints defined by Human3.6M are used for computing PA-MPJPE and MPJPE 

### ISSUE THREAD

**Issue by Oruka94** [hongsukchoi/TCMR_RELEASE#39]
Hello.
You mentioned in your paper that you used 14 joints defined by Human3.6M for computing PA-MPJPE and MPJPE. I wonder those joints are which of the 17 joints in Human3.6M? Did you exclude H36M_NAMES[15] = 'Head', H36M_NAMES[14] = 'Neck/Nose', and H36M_NAMES[12] = 'Spine'?

**Comment by hongsukchoi** [comment]
I followed the previous literature

Please refer to here: https://github.com/hongsukchoi/Pose2Mesh_RELEASE/blob/d2c031d6ec7ab409f5981d7bef0b23444ec40e2e/data/Human36M/dataset.py#L51

**Comment by Oratacth** [comment]
> I followed the previous literature
> 
> Please refer to here: https://github.com/hongsukchoi/Pose2Mesh_RELEASE/blob/d2c031d6ec7ab409f5981d7bef0b23444ec40e2e/data/Human36M/dataset.py#L51

When I validate, why does this happen

Traceback (most recent call last):
  File "train.py", line 138, in <module>
    main(cfg)
  File "train.py", line 130, in main
    debug_freq=cfg.DEBUG_FREQ,
  File "D:\PROJECT\TCMR\lib\core\trainer.py", line 338, in fit
    self.validate()
  File "D:\PROJECT\TCMR\lib\core\trainer.py", line 300, in validate
    target_j3d = target['kp_3d'].view(-1, n_kp, 3).cpu().numpy()
RuntimeError: shape '[-1, 49, 3]' is invalid for input of size 1344

**Comment by hongsukchoi** [comment]
It seems you have downloaded wrong data
